version: "3"
services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  tilenol:
    image: stationa/tilenol:latest
    command: run
    environment:
      TILENOL_ENABLE_CORS: "true"
    volumes:
      - ./tilenol.yml:/tilenol.yml
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - postgis
