name: CI
on: [ push, pull_request ]

jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18' ]  # TODO: Add more checks for broader Go support?

    steps:
      - name: Pull source
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build ${{ matrix.go-version }}
        run: go build -v ./...

      - name: Test ${{ matrix.go-version }}
        run: go test -v ./...

  build-and-push-docker:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Pull source
        uses: actions/checkout@v3

      - name: Log in to the Github container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          # NOTE: This can also be triggered for multiple registries, e.g. DockerHub
          tags: |
            type=raw,value=devel,enable={{is_default_branch}}
            type=raw,value=devel-{{ branch }}=enable={{!is_default_branch}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern={{raw}},value=latest
          images: ghcr.io/stationa/tilenol

      - name: Build and push images
        if: github.event_name == 'push'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
