name: CI
on:
  push:
    branches:
      - main
      - gh-32

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18' ]  # TODO: Add more checks for broader Go support?

    steps:
      - name: Pull source
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build ${{ matrix.go-version }}
        run: go build -v ./...

      - name: Test ${{ matrix.go-version }}
        run: go test -v ./...
